ALTER TABLE FACTURE ADD CONSTRAINT FK_FACT_LIG FOREIGN KEY (compte_ligue) REFERENCES LIGUE (numcompte) ON DELETE CASCADE;

ALTER TABLE LIGUE_FACTURE ADD CONSTRAINT FK_LIGFA_FACT FOREIGN KEY (numfacture) REFERENCES FACTURE (numfacture) ON DELETE CASCADE;

ALTER TABLE LIGUE_FACTURE ADD CONSTRAINT FK_LIGFA_PRES FOREIGN KEY (code_pres) REFERENCES PRESTATION (code) ON DELETE CASCADE;

ALTER TABLE LIGUE ADD CONSTRAINT FK_LIG_TRES FOREIGN KEY (numtreso) REFERENCES TRESORIER (numtreso) ON DELETE CASCADE;
